import {
  SiNextdotjs,
  SiReact,
  SiLaravel,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiPhp,
  SiMysql,
  SiPostgresql,
  SiSupabase,
  SiNodedotjs,
  SiTailwindcss,
  SiBootstrap,
  SiPostman,
  SiFigma,
  SiAdobeillustrator,
  SiCoreldraw,
  SiCanva,
  SiGit,
  SiGithub,
  SiExpress,
} from "react-icons/si";

export const techIcons = {
  "Next.js": SiNextdotjs,
  React: SiReact,
  Laravel: SiLaravel,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  PHP: SiPhp,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  Supabase: SiSupabase,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "Tailwind CSS": SiTailwindcss,
  Bootstrap: SiBootstrap,
  Postman: SiPostman,
  Figma: SiFigma,
  "Adobe Illustrator": SiAdobeillustrator,
  CorelDRAW: SiCoreldraw,
  Canva: SiCanva,
  Git: SiGit,
  "Git / GitHub": SiGithub,
  "Node.js / Express.js": SiNodedotjs,
  "MySQL / PostgreSQL": SiMysql,
  "Figma / Canva": SiFigma,
  "Adobe Illustrator / CorelDRAW": SiAdobeillustrator,
};

export function getTechIcon(name) {
  return techIcons[name] || null;
}
